- name: copy mongodb repo
  copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo   
- name: install mongodb server
  package:
    name: mongodb-org
    state: present
- name: allow remote connections
  lineinfile:
    path: /etc/mongod.conf
    regexp: '^ *bindIp:'
    line: '  bindIp: 0.0.0.0'
    backup: yes
- name: start and enable mongodb
  service:
    name: mongod
    state: restarted
    enabled: yes