[local]
localhost

[mongodb]
mongodb.nasika.site

[redis]
redis.nasika.site

[mysql]
mysql.nasika.site

[rabbitmq]
rabbitmq.nasika.site

[catalogue]
catalogue.nasika.site

[user]
user.nasika.site

[cart]
cart.nasika.site

[shipping]
shipping.nasika.site

[payment]
payment.nasika.site

[frontend]
frontend.nasika.site